       
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
  
  <link href="http://fast.fonts.com/cssapi/59baa84c-fd68-4947-98cd-ee547f43a52f.css" rel="stylesheet" type="text/css" />
  
  <link href="css/brand.css" rel="stylesheet" media="all" />
  <link href="css/layout-mobile.css" rel="stylesheet" media="screen" />
  <link href="css/layout-tablet.css" rel="stylesheet" media="screen and (min-width: 480px)" />
  <link href="css/layout-largetablet.css" rel="stylesheet" media="screen and (min-width: 720px)" />
  <link href="css/layout-desktop.css" rel="stylesheet"  media="screen and (min-width: 980px)" />
  <link href="css/layout-largedesktop.css" rel="stylesheet"  media="screen and (min-width: 1080px)" />
  
  <link href="css/print.css" rel="stylesheet" media="print" />
  
  <script>var badIE = false;</script>
  <!--[if (lt IE 8)]>
  <script type="text/javascript">var badIE = true;</script>
  <![endif]-->
  
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
  <script src="js/jquery.hoverIntent.js"></script>
  <script src="js/main.js"></script>
  
  <!--[if (IE)]>
  <link href="css/ie.css" rel="stylesheet" />
  <![endif]-->
  <!--[if (IE 7)|(IE 8)]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <link href="css/layout-tablet.css" rel="stylesheet" media="screen" />
  <link href="css/layout-largetablet.css" rel="stylesheet" media="screen"  />
  <link href="css/layout-desktop.css" rel="stylesheet" media="screen"  />
  <link href="css/layout-desktop-full.css" rel="stylesheet" media="screen" />
  <link href="css/ie8.css" rel="stylesheet" />
  <![endif]-->
  <!--[if (IE 7)]>
  <link href="css/ie7.css" rel="stylesheet" />
  <![endif]-->
  <!--[if (lt IE 7)]>
  <link href="css/ie6.css" rel="stylesheet" />
  <![endif]-->
