 <footer id="footer">
  <div class="wrap">
   <section class="contact">
    <h3>Contact</h3>
   
    <span class="tel">+44 (0)23 4353433</span>
    <address>
     <span>International Headquarters</span>
     <span>Tupolevlaan 24</span>
     <span>1119 NX Schilphol-Rijk</span>
     <span>The Netherlands</span>
    </address>
   
    <a class="btn" href="#">Other Countries <b>&gt;</b></a>
   </section>
  
   <section class="shortcuts">
    <h3>Shortcuts</h3>
   
    <ul>
     <li><a href="#">Investor Relations</a></li>
     <li><a href="#">Careers</a></li>
     <li><a href="#">Terms of use</a></li>
     <li><a href="#">Site map</a></li>
     <li><a href="#">Privacy Policy</a></li>
    </ul>
   </section>
  
   <section class="techExcellence">
    <h3>Technical Excellence</h3>
   
    <ul>
     <li><a href="#">Awards &amp; accreditations</a></li>
     <li><a href="#">Carrier neutrality</a></li>
     <li><a href="#">Pan European coverage</a></li>
     <li><a href="#">Support</a></li>
    </ul>
   </section>
   
  <section class="twitter">
    <img src="img/twitter.png">
   </section>
   
   
  </div>
 </footer>
 
 <footer id="copyright">
  <p>&copy; Interxion MMXII.  All Rights Reserved.</p>
 </footer>