 <header id="header">
  <div class="wrap">
   <h1 id="branding">
    <a href="index.php" title="Go to Homepage"><img src="img/logo.png" alt="Interxion" /></a>
   </h1>
  
   <nav id="mobileNav">
    <ul>
     <li><a href="#pNav" id="toggleSiteMenu">Site Menu</a></li>
     <li class="selectCountry"><a href="#countryNav" id="toggleCountryNav" class="england">Select Country</a></li>
     <li class="searchSite"><a href="#siteSearch" id="toggleSiteSearch">Search Site</a></li>
    </ul>
   </nav>

   <nav id="pNav">
    <ul>
	
		<li class="sectors"><a href="sectors.php">Sectors</a>
			<ul><li>
			<img src="img/flyout_sectors.png">
			</li></ul>
		</li>
			
		<li class="locations"><a href="locations.php">Locations</a>
			<ul><li>
			<a href="locations.php"><img src="img/flyout_locations.png"></a>
			</li></ul>
		</li>
			
		 <li class="datacentres"><a href="#">Data Centres</a>
			<ul><li>
			<img src="img/flyout_datacentres.png">
			</li></ul>
		</li>
			
		<li class="whyinterxion"><a href="#">Why Interxion?</a>
			<ul><li>
			<img src="img/flyout_whyinterxion.png">
			</li></ul>
		</li>
			
		<li class="customers"><a href="customers.php">Customers</a></li>
	 
    </ul>
   </nav>
   
 
  <div id="tools">
   <div class="wrap">
    <nav id="toolsNav">
     <ul>
      <li class="aboutus"><a href="aboutus.php">About Us</a></li>
      <li><a href="#">Investor Relations</a></li>
      <li><a href="#">Customer Portal</a></li>
      <li id="contactForm" class="noJS"><a href="#">Contact Us</a>
	  	<div id="contactus"><img src="img/contactus.jpg"></div>
	  </li>
     </ul>
    </nav>
   
    <form id="siteSearch">
     <input type="text" placeholder="Search site" />
	 <INPUT type="image" name="search" src="img/mag.png" border="0">
    </form>
   
    <nav id="countryNav" class="noJS">
     <a class="selectCountry england" href="#">Select Country</a>
    
     <ul>
      <li><a class="austria" href="#">Austria</a></li>
      <li><a class="belgium" href="#">Belgium</a></li>
      <li><a class="denmark" href="#">Denmark</a></li>
      <li><a class="england" href="#">England</a></li>
      <li><a class="france" href="#">France</a></li>
      <li><a class="germany" href="#">Germany</a></li>
      <li><a class="ireland" href="#">Ireland</a></li>
      <li><a class="netherlands" href="#">Netherlands</a></li>
      <li><a class="spain" href="#">Spain</a></li>
      <li><a class="switzerland" href="#">Switzerland</a></li>
      <li><a class="sweden" href="#">Sweden</a></li>
     </ul>
    </nav>
   </div>
  </div>
 </header>
 
 